datas = """
undo원상태로돌리다
undermine약화[손상]시키다
instance사례,경우
quarrel다투다,언쟁을벌이다
interpersonal대인관계에관련된
compact조밀한,촘촘한
medium매체,수단
ubiquitous어디에나있는
contrast대조하다,대조를보이다
mean의도하다
hygiene위생
hue색조,빛깔
crude천연그대로의

manner방법,방식
abnormal비정상적인,이상한
acoustic청각의,음향의
drive(어떤방향으로)몰다
moral((pl.))도덕,윤리
deceptive속이는,기만적인,오해를사는
curl(몸을)웅크리다
appropriate적절한
influx(사람,자금등의)유입,밀려듦
germinate싹이트다,발아하다
psyche정신,마음
headquarters본사,본부
immature미숙한
impede저해[방해]하다
imminent임박한,절박한

observe(법률,규칙등을)준수하다
native출생지의,토착의
radiant빛나는,환한
specific명확한,구체적인,특정한
relative상대적인
era시대,연대
shiver(추위,공포등으로)몸을떨다
perceive지각[인지]하다
assume(책임,역할을)맡다
conduct(열,전기를)전도하다
eradicate근절하다,뿌리뽑다
promote진급[승진]시키다
irrational비이성적인,분별이없는
bear참다,견디다
heritage(사회적,문화적)유산,전통
fast단식[금식]하다
conflict충돌,갈등

consequence중요성,중대함
plausible이치에맞는,그럴듯한
narrow(폭이)좁은
stock비축하다,저장하다
invariable변함없는
indicate나타내다,보여주다
extent정도,규모
content만족[자족]하는
scale저울
institution기관,협회
premise전제
fallacy오류,착오
merely단지,그저
tantrum성질,짜증
setback방해,실패,좌절
vibrant활기찬,생명력이넘치는
due~하기로예정된
decisive결정적인,중대한
prolonged오래계속되는,장기적인
camouflage위장,속임수
rigorous정확한,정밀한
firm확고한
momentous중대한,중요한
feature(배우를)주연시키다
deforestation삼림벌채
tactic전략,작전
elastic탄력[신축성]있는
mist안개

vivid(상상력이)활발한
concentrate응축[농축]하다
demonstrate입증하다
strike파업
aesthetic심미적인,미학적인
derive~에서비롯되다
metabolic신진[물질]대사의
appliance(가정용)기기,장치,가전제품
identical동일한,똑같은
shift변화
natal출생의
tremble떨(리)다
intense극심한,강렬한
recess휴식,휴회
arrogant오만한,건방진
startle깜짝놀라게하다
staple주된,주요한
attribute(~의)덕분[탓]으로돌리다

endeavor노력하다,시도하다
anticipate예상[기대]하다
optimistic낙관적인
practical실용적인,유용한
contemporary동시대의
successive연속적인,연이은
innovation혁신,쇄신
notion개념,관념,생각
expenditure소비,소모
conference회의,학회
currency통화,화폐
compatible양립[공존]할수있는
falsify거짓임을입증하다
blaze불길,화재
precisely정확히,정밀하게
engage(마음을)사로잡다
volume부피,양
itinerary여행일정표
intact손상되지않은,그대로의
narrative이야기,서술
mischief나쁜짓,장난
bold용감한,대담한

yield양보하다
definitive최종적인,확정적인
convey(생각,감정등을)전달하다
admit인정[시인]하다
charge(대가,요금을)청구하다
howl(개,늑대등이)길게짖다
crucial결정적인,중대한
conventional전통[관습]적인,틀에박힌
duplicate되풀이하다
induce초래하다
frustrated좌절한,짜증이난,불만스러운
greed탐욕,욕심
stern엄격한,단호한
contrary반대되는
facility((pl.))시설,설비
seal밀봉하다,밀폐하다
inclination경향,의향
candidate후보자,지원자
variation변화,변형
altitude고도
epic서사시,대작
penetrate침투하다,뚫고들어가다
remark언급하다,말하다
account(비율을)차지하다
distinct별개의,구별되는
subordinate종속된,하위의,부수적인
ease편하게하다,경감시키다
retrieve되찾다,회복하다

appeal호소하다
ignite불이붙다,불을붙이다
deceased사망한
stereotype고정관념
ethnic민족의,인종의
plot구성,줄거리
employ이용하다
commit(범죄등을)저지르다
vendor판매회사
behalf측,편,이익
magnificent장엄한,훌륭한
intend의도[작정]하다
net에누리없는,순~,실~
rational합리적인,이성적인
diminish줄어들다,감소하다
manifest나타내다,드러내다
underlie~의기초가되다
longevity장수
assess평가하다
colony식민지
consciousness의식,자각
credit칭찬,인정,공로
modest그다지대단하지않은,보통의
impersonal인간미없는,비인격적인
suppose가정[상상]하다
earthly현세의,세속적인
inherent타고난,내재하는
momentary순간적인,잠깐의
regard(~으로)간주하다,여기다
entice유도[유인]하다

breathtaking숨막히는,깜짝놀랄만한
hybrid(동식물의)잡종
sophisticated정교한,복잡한
polygraph거짓말탐지기
secure안심하는,안전한
indifferent무관심한
vital생명유지에필수적인
conscience양심
neglect무시하다,도외시하다
proportion비율
expense돈,비용
pointless무의미한,할가치가없는
devote바치다,전념하다
outgoing외향적인,사교적인
outdated구식의,시대에뒤진
priority우선(권)
relevant관련된,적절한
physician내과의사
omission소홀,태만
radioactive방사능[성]의
guarantee보장하다,약속하다
classical인문적인
radiation(열,에너지등의)복사,방사(선)
pastime취미,오락
instinct본능,직관
ground~에근거를두다
malnutrition영양실조
midwife산파,조산사
inflict(괴로움등을)가하다
paralyzed마비된

disposable1회용의,쓰고버리는
urge촉구하다,재촉하다
illusion오해,착각
compensate보상[배상]하다
facilitate가능[용이]하게하다,촉진하다
inferior질낮은,열등한
shortcut지름길,손쉬운방법
welfare복지,행복
molecule분자
sob흐느껴울다
reasonable적당한,(가격이)알맞은
benevolent자애로운
remarkable주목할만한,놀랄만한
resort의지하다,호소하다
thermometer온도계,체온계
humidity습도,습기
trim(깎아서)다듬다,손질[정돈]하다
deadlock교착상태
transit운송,수송
application적용,사용
renowned유명한,명성있는
rip찢다,뜯어내다
homogeneous동종의,동질적인
court법정,법원
illustrate설명[실증]하다
conjecture추측
psychic마음의,정신의
profess공언[선언]하다
rally집결[단결]하다
pollinate수분하다
refract굴절시키다
masculine남자다운
rein통제하다,제어하다
intolerance참을수없음,편협
shortcoming((pl.))결점,단점

vigorous활발한,활기찬
withstand저항하다,견뎌내다
lull달래다,안심[진정]시키다
betrayal배신,배반
tune(악기를)조율하다
adjoin인접하다,붙어있다
amplify증폭시키다,확대하다
confront직면하다,맞서다
accuse고발[기소]하다
dominate지배하다
hypocrisy위선
adorn꾸미다,장식하다
exponential(증가율이)기하급수적인
immigrant(외국으로부터의)이민자,이주민
isolate격리하다,고립시키다
phrase구,관용구
portion부분,일부
fiber섬유(질)
radical근본적인
fright두려움,공포
resolve결심하다
affliction고통,괴로움
severe심각한
abolition(법률,제도의)폐지,폐기
hierarchical계층의,계급에따른
weary지친,피곤한
evacuation대피,철수
murmur속삭이다,중얼거리다
shed(허물,옷을)벗다
numerical수의,숫자로표시한
brief간결한,간단한
fade시들다,약해지다
diffuse분산되다[시키다],확산되다[시키다]

amuse즐겁게하다
blush얼굴을붉히다
decay부패[부식]하다
obedient순종적인,복종하는
disturb방해하다
familiarity익숙함,친밀
buoyant부력이있는,물에뜰수있는
chamber방,실
bully(약자를)괴롭히는사람
liberal자유민주적인
void무효의
norm((pl.))규범
catastrophe참사,재앙
prosperity번영,번성,부
cozy편안한,안락한
contempt경멸,멸시
scatter흩뿌리다,흩어지게하다
underrate과소평가하다
cynical냉소적인
trigger촉발시키다
vague애매한,모호한
compromise타협,화해,양보
incorporate포함[편입]하다
commodity상품,물품
esteem존경[존중]하다
egocentric자기중심적인
nocturnal밤의,야행성의
salute경의를표하다
luxuriant무성한,풍성한
deposit예금[예치]하다
oppress압박[억압]하다
ordeal시련,고난"""